# -*- coding: utf-8 -*-
"""Copy of Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NsS2HnOWIQ-2Pg8rw6ISAcDyK9OdfnGR
"""

import pandas as pd
from datetime import datetime
from IPython.display import display # Assuming display is needed for Colab output

# Define the variables required for the meeting minutes
meeting_title = "Project Alpha Kick-off Meeting"
date = "2023-10-27"
time = "10:00 AM PST"
participants_list = ["Alice", "Bob", "Charlie"]
agenda_list = ["Introductions", "Project Goals", "Timeline Discussion", "Next Steps"]
decisions_list = ["Approved project scope", "Assigned initial tasks"]
actions_list = ["Alice to prepare project charter", "Bob to set up weekly syncs"]
prepared_by = "AI Assistant"

# Create structured meeting minutes
minutes = {
    "Meeting Title": meeting_title,
    "Date": date,
    "Time": time,
    "Participants": ", ".join(participants_list),
    "Agenda":"; ".join(agenda_list),
    "Decisions Taken": "; ".join(decisions_list),
    "Action Items":"; ".join(actions_list),
    "Prepared By": prepared_by,
    "Generated On": datetime.now().strftime("%d-%m-%Y %H:%M:%S")
}

# Convert to DataFrame
df = pd.DataFrame(list(minutes.items()), columns=["Field", "Details"])
print("\n Meeting Minutes Generated Successfully\n")
display(df)

# Save as CSV
df.to_csv("meeting minutes.csv", index=False)
print("\n File saved as meeting minutes.csv")

# Meeting Minutes Generator
#
import pandas as pd
from datetime import datetime
print("MEETING MINUTES GENERATOR\n")

# User Inputs
meeting_title = input("Enter meeting title: ")
date = input("Enter meeting date (DD-MM-YYYY): ")
time = input("Enter meeting time: ")
participants = input("Enter participants (comma separated): ")
agenda = input("Enter agenda points (comma separated): ")
decisions = input("Enter decisions taken (comma separated): ")
action_items = input("Enter action items (comma separated): ")
prepared_by = input("Prepared by: ")

# Process Inputs
participants_list = [p.strip() for p in participants.split(",") if p.strip()]
agenda_list = [a.strip() for a in agenda.split(",") if a.strip()]
decisions_list = [d.strip() for d in decisions.split(",") if d.strip()]
actions_list = [a.strip() for a in action_items.split(",") if a.strip()]

# Create structured meeting minutes
# (The rest of the code for creating minutes and saving will follow here)

import pandas as pd
import random

print("TIMETABLE GENERATOR\n")

# User Inputs
subjects_input = input("Enter subjects (comma separated): ")
days_input = input("Enter days (comma separated): ") # Corrected assignment
periods_per_day = int(input("Enter number of periods per day: ")) # Corrected assignment

# Process Inputs
subjects = [s.strip() for s in subjects_input.split(",") if s.strip()] # Corrected assignment
days = [d.strip() for d in days_input.split(",") if d.strip()] # Corrected assignment

# Validation
if not subjects or not days or periods_per_day <= 0: # Corrected if statement syntax
    print("Invalid input. Please try again.")
else:
    timetable = {}
    for day in days:
        timetable[day] = random.choices(subjects, k=periods_per_day) # Corrected k-periods_per_day

    # Create DataFrame
    df = pd.DataFrame(timetable)
    df.index = [f"Period {i+1}" for i in range(periods_per_day)]
    print("\nTimetable Generated Successfully\n")
    display(df) # Placed on a new line for clarity

    # Save timetable
    df.to_csv("timetable.csv")
    print("\nTimetable saved as timetable.csv") # Placed on a new line for clarity

!pip install transformers torch pandas
from transformers import pipeline
import pandas as pd


#load sentiment analysis model
sentiment = pipeline("sentiment-analysis")
#sample product review(you can change only this later)
reviews = """The laptop starts quickly and works smoothly for daily tasks.
The screen quality is clear and good for watching videos.
Battery backup is average and needs charging often.
The fan makes noise when many apps are running.
Overall, it is a good laptop for students but not for gaming.
"""


#spilt review into sentences
sentences = reviews.split(".")
pros = []
cons = []
for s in sentences:
  s = s.strip()
  if s == "":
    continue
  result = sentiment(s)[0]
  if result["label"] == "POSITIVE": # Corrected typo from POSTIVE to POSITIVE
    pros.append(s)
  elif result["label"] == "NEGATIVE":
    cons.append(s)
#Take only 2 pros and 2 cons
pros = pros[:2]
cons = cons[:2]


#create table
df = pd.DataFrame({
    "Pros": pros,
    "Cons": cons
})
df

!pip install transformers torch


from transformers import pipeline
#load text generation model(GenAI)
generator = pipeline(
    "text-generation",
    model="gpt2"
)
#input prompt
prompt = "Artificial Intelligence in finance will"
#generate text
result = generator(prompt,max_length=50,num_return_sequences=1)
print("AI Generated Text :")
print(result[0]['generated_text'])